name: turnover
channels:
 - bioconda
 - plotly
 - conda-forge
 - defaults
dependencies:
 - python=3.12.6
 - pip=25.2
 - numpy=2.3.2
 - biopython=1.84
 - plotly=6.2.0
 - meme=5.5.8
 - dash=3.1.1
 - dash-bootstrap-components=2.0.3
 - dash-core-components=2.0.0
 - dash-html-components=2.0.0
 - pip:
   - loguru
